const images = {
  acuario: require("./acuario.png"),
  aries: require("./aries.png"),
  cancer: require("./cancer.png"),
  capricornio: require("./capricornio.png"),
  escorpion: require("./escorpion.png"),
  geminis: require("./geminis.png"),
  leo: require("./leo.png"),
  libra: require("./libra.png"),
  piscis: require("./piscis.png"),
  sagitario: require("./sagitario.png"),
  tauro: require("./tauro.png"),
  virgo: require("./virgo.png"),
  tarot: require("./tarot.png"),
  universe: require("./bg-sky.jpg"),
  carta_de_tarot: require("./carta-de-tarot.png"),
  bola_de_cristal: require("./bola-de-cristal.png"),
  cartas_de_tarot: require("./cartas-de-tarot.png"),
  zodiacs: require("./zodiacs.png"),
  compatibilidad: require("./compatibilidad.png"),
  constelacion: require("./constelacion.png"),
  constelacion_daily: require("./constelacion_daily.png"),
  constelacion_general: require("./constelacion_general.png"),
};

export default images;
